# Generated by Django 5.1.6 on 2025-03-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_customerusers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerusers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
