# Generated by Django 5.1.6 on 2025-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_slots_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'รอยืนยัน'), ('confirmed', 'ยืนยันแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
