# Generated by Django 5.1.6 on 2025-02-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='booked', max_length=20),
        ),
    ]
