# Generated by Django 5.1.6 on 2025-02-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_reservation_user_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
